ALTER TYPE "WorkflowRunStatus" ADD VALUE IF NOT EXISTS 'QUEUED' BEFORE 'RUNNING';
ALTER TYPE "WorkflowRunStatus" ADD VALUE IF NOT EXISTS 'WAITING' BEFORE 'SUCCEEDED';
ALTER TYPE "WorkflowRunStatus" ADD VALUE IF NOT EXISTS 'CANCELLED' AFTER 'PAUSED';
